"""
Django settings for KUKUCONNECT project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
import dj_database_url
from dotenv import load_dotenv  # <-- ADDED: To read .env file

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ADDED: Load environment variables from .env file for local development
load_dotenv(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# FIXED (A05): Now reads from environment variable.
# !! YOU MUST CHANGE THIS VALUE in your .env and on Render !!
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# FIXED (A05): Now reads from environment variable, defaults to False.
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# FIXED (A05): Now reads from environment variable.
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'django_daraja',
    'drf_yasg',
    'users',
    'profiles',
    'products',
    'payments',
    'chatbot',
]

# ---
# <-- FIX: 1 of 2
# Moved 'corsheaders.middleware.CorsMiddleware' to the top.
# This ensures it runs before 'CommonMiddleware' and prevents
# the 301 redirects on your OPTIONS requests.
# ---
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # <-- MOVED HERE
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'corsheaders.middleware.CorsMiddleware', # <-- REMOVED FROM HERE
]

ROOT_URLCONF = 'KUKUCONNECT.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'KUKUCONNECT.wsgi.application'

# FIXED (A05): Set to False. This forces Django to use the explicit list below.
CORS_ALLOW_ALL_ORIGINS = False

# FIXED (A05): Now reads from environment variable.
CORS_ALLOWED_ORIGINS = os.environ.get('CORS_ALLOWED_ORIGINS', 'http://localhost:5173,http://localhost:3000').split(',')


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# This logic is good and already reads from environment variables. No changes needed.
DATABASE_URL = os.getenv('DATABASE_URL')

if DATABASE_URL:
    # Use the database settings from DATABASE_URL in production
    DATABASES = {
        
        'default': dj_database_url.config(default=DATABASE_URL)
    }
else:
    # Fallback to local PostgreSQL settings (for development)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME'),
            'USER': os.getenv('DB_USER'),
            'PASSWORD': os.getenv('DB_PASSWORD'),
            'HOST': os.getenv('DB_HOST'),
            'PORT': os.getenv('DB_PORT'),
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

# ---
# FIXED: A07: IDENTIFICATION AND AUTHENTICATION FAILURES
# Updated to enforce stronger password policies.
# ---
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        # Enforce a stronger minimum length
        'OPTIONS': {
            'min_length': 10,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

#Custom user model 
AUTH_USER_MODEL = 'users.CustomUser'

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# settings.py

STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=1440),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=2),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    # This is correct. It reads the SECRET_KEY variable from the top of this file.
    'SIGNING_KEY': SECRET_KEY, 
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}

# ---
# NEWLY ADDED
# FIXED: A09: SECURITY LOGGING AND MONITORING FAILURES
# Configures logging to capture warnings, errors, and security events.
# In production (on Render), this will output to the console,
# which is captured by Render's Log Stream.
# ---
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    
    # How to format the log messages
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    
    # Where to send the logs
    'handlers': {
        # Handler 1: Log to the console (for Render)
        'console': {
            'level': 'INFO', # Capture INFO and above
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        # Handler 2: Log to a file (for local debugging)
        'file': {
            'level': 'WARNING', # Only log WARNING and above to the file
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'django_security.log'),
            'formatter': 'verbose',
        },
    },
    
    # Which loggers to use
    'loggers': {
        # 1. The general Django logger
        'django': {
            'handlers': ['console', 'file'], # Send to both console and file
            'level': 'INFO', # Log INFO, WARNING, ERROR, CRITICAL
            'propagate': True,
        },
        # 2. A specific logger for security events
        'django.security': {
            'handlers': ['console', 'file'],
            'level': 'WARNING', # Capture all security warnings
            'propagate': False,
        },
        # 3. Logger for your own apps (optional, but good practice)
        'users': {
            'handlers': ['console'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'products': {
            'handlers': ['console'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'profiles': {
            'handlers': ['console'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
    },
}


# This section is already correctly reading from environment variables. No changes needed.
MPESA_ENVIRONMENT = os.environ.get('MPESA_ENVIRONMENT')
MPESA_CONSUMER_KEY = os.environ.get('MPESA_CONSUMER_KEY')
MPESA_CONSUMER_SECRET = os.environ.get('MPESA_CONSUMER_SECRET')
MPESA_SHORTCODE = os.environ.get('MPESA_SHORTCODE')
MPESA_EXPRESS_SHORTCODE = os.environ.get('MPESA_EXPRESS_SHORTCODE')
MPESA_SHORTCODE_TYPE = os.environ.get('MPESA_SHORTCODE_TYPE')
MPESA_PASSKEY = os.environ.get('MPESA_PASSKEY')
MPESA_INITIATOR_USERNAME = os.environ.get('MPESA_INITIATOR_NAME')
MPESA_INITIATOR_SECURITY_CREDENTIAL = os.environ.get('MPESA_INITIATOR_PASSWORD')
MPESA_PHONE_NUMBER = os.environ.get('MPESA_PHONE_NUMBER')

# ---
# FIXED: A02: CRYPTOGRAPHIC FAILURES
# Added Production-Only Security Settings to enforce HTTPS.
# ---
if not DEBUG:
    # ---
    # <-- FIX: 2 of 2
    # Corrected the typo 'httpsfs' to 'https'
    # ---
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    
    # 1. Force all connections to be over HTTPS (SSL)
    SECURE_SSL_REDIRECT = True
    
    # 2. Tell the browser to only send session cookies over HTTPS
    SESSION_COOKIE_SECURE = True
    
    # 3. Tell the browser to only send the CSRF cookie over HTTPS
    CSRF_COOKIE_SECURE = True
    
    # 4. Enable HTTP Strict Transport Security (HSTS)
    SECURE_HSTS_SECONDS = 3600  # 1 hour
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True