# Generated by Django 5.1.4 on 2024-12-17 19:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyerprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='buyerprofile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='buyerprofile',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='business_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='preferred_products',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='farm_name',
            field=models.CharField(default='Farm Name', max_length=255),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='farm_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='buyerprofile',
            name='phone_number',
            field=models.CharField(default='Phone Number', max_length=15),
        ),
        migrations.AlterField(
            model_name='buyerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='location',
            field=models.CharField(default='Location', max_length=255),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='phone_number',
            field=models.CharField(default='Phone Number', max_length=15),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
